/** Communes du département des Bouches-du-Rhône (13) — liste de référence pour l'import SIG. */
export interface CommuneOption {
  inseeCode: string;
  name: string;
}

export const DEPARTMENT_COMMUNES: CommuneOption[] = [
  { inseeCode: '13001', name: 'Aix-en-Provence' },
  { inseeCode: '13002', name: 'Allauch' },
  { inseeCode: '13003', name: 'Alleins' },
  { inseeCode: '13004', name: 'Arles' },
  { inseeCode: '13005', name: 'Aubagne' },
  { inseeCode: '13006', name: 'Auriol' },
  { inseeCode: '13007', name: 'Aurons' },
  { inseeCode: '13008', name: 'Barbentane' },
  { inseeCode: '13009', name: 'Beaurecueil' },
  { inseeCode: '13010', name: 'Belcodène' },
  { inseeCode: '13011', name: 'Berre-l\'Étang' },
  { inseeCode: '13012', name: 'Bouc-Bel-Air' },
  { inseeCode: '13013', name: 'Bouilladisse' },
  { inseeCode: '13014', name: 'Cabriès' },
  { inseeCode: '13015', name: 'Cadenet' },
  { inseeCode: '13016', name: 'Cadolive' },
  { inseeCode: '13019', name: 'Carnoux-en-Provence' },
  { inseeCode: '13021', name: 'Cassis' },
  { inseeCode: '13022', name: 'Ceyreste' },
  { inseeCode: '13023', name: 'Charleval' },
  { inseeCode: '13024', name: 'Châteauneuf-le-Rouge' },
  { inseeCode: '13025', name: 'Châteauneuf-les-Martigues' },
  { inseeCode: '13026', name: 'Châteaurenard' },
  { inseeCode: '13027', name: 'La Ciotat' },
  { inseeCode: '13028', name: 'Cornillon-Confoux' },
  { inseeCode: '13029', name: 'Coudoux' },
  { inseeCode: '13030', name: 'Cuges-les-Pins' },
  { inseeCode: '13031', name: 'La Destrousse' },
  { inseeCode: '13032', name: 'Éguilles' },
  { inseeCode: '13033', name: 'Ensuès-la-Redonne' },
  { inseeCode: '13034', name: 'Eyguières' },
  { inseeCode: '13035', name: 'Eyrières' },
  { inseeCode: '13036', name: 'Eyragues' },
  { inseeCode: '13037', name: 'Fontvieille' },
  { inseeCode: '13038', name: 'Fuveau' },
  { inseeCode: '13039', name: 'Gardanne' },
  { inseeCode: '13040', name: 'Gémenos' },
  { inseeCode: '13041', name: 'Gignac-la-Nerthe' },
  { inseeCode: '13042', name: 'Grans' },
  { inseeCode: '13043', name: 'Greasque' },
  { inseeCode: '13044', name: 'Istres' },
  { inseeCode: '13045', name: 'Jouques' },
  { inseeCode: '13046', name: 'Lamanon' },
  { inseeCode: '13047', name: 'Lambesc' },
  { inseeCode: '13048', name: 'Lançon-Provence' },
  { inseeCode: '13049', name: 'Mallemort' },
  { inseeCode: '13050', name: 'Marignane' },
  { inseeCode: '13051', name: 'Marseille' },
  { inseeCode: '13052', name: 'Martigues' },
  { inseeCode: '13053', name: 'Meyreuil' },
  { inseeCode: '13054', name: 'Mimet' },
  { inseeCode: '13055', name: 'Miramas' },
  { inseeCode: '13056', name: 'Mouriès' },
  { inseeCode: '13057', name: 'Noves' },
  { inseeCode: '13058', name: 'Orgon' },
  { inseeCode: '13059', name: 'Paradou' },
  { inseeCode: '13060', name: 'Pélissanne' },
  { inseeCode: '13061', name: 'Les Pennes-Mirabeau' },
  { inseeCode: '13062', name: 'Peypin' },
  { inseeCode: '13063', name: 'Peyrolles-en-Provence' },
  { inseeCode: '13064', name: 'Plan-de-Cuques' },
  { inseeCode: '13065', name: 'Port-de-Bouc' },
  { inseeCode: '13066', name: 'Port-Saint-Louis-du-Rhône' },
  { inseeCode: '13067', name: 'Puyloubier' },
  { inseeCode: '13068', name: 'Le Puy-Sainte-Réparade' },
  { inseeCode: '13069', name: 'Rognac' },
  { inseeCode: '13070', name: 'Rognes' },
  { inseeCode: '13071', name: 'Roquefort-la-Bédoule' },
  { inseeCode: '13072', name: 'Roquevaire' },
  { inseeCode: '13073', name: 'Rousset' },
  { inseeCode: '13074', name: 'Saint-Antonin-sur-Bayon' },
  { inseeCode: '13075', name: 'Saint-Cannat' },
  { inseeCode: '13076', name: 'Saint-Chamas' },
  { inseeCode: '13077', name: 'Saint-Estève-Janson' },
  { inseeCode: '13078', name: 'Saint-Marc-Jaumegarde' },
  { inseeCode: '13079', name: 'Saint-Martin-de-Crau' },
  { inseeCode: '13080', name: 'Saint-Mitre-les-Remparts' },
  { inseeCode: '13081', name: 'Saint-Paul-lès-Durance' },
  { inseeCode: '13082', name: 'Saint-Rémy-de-Provence' },
  { inseeCode: '13083', name: 'Saint-Savournin' },
  { inseeCode: '13084', name: 'Saint-Victoret' },
  { inseeCode: '13085', name: 'Salon-de-Provence' },
  { inseeCode: '13086', name: 'Sausset-les-Pins' },
  { inseeCode: '13087', name: 'Sénas' },
  { inseeCode: '13088', name: 'Septèmes-les-Vallons' },
  { inseeCode: '13089', name: 'Simiane-Collongue' },
  { inseeCode: '13090', name: 'Tarascon' },
  { inseeCode: '13091', name: 'Trets' },
  { inseeCode: '13092', name: 'Vauvenargues' },
  { inseeCode: '13093', name: 'Velaux' },
  { inseeCode: '13094', name: 'Venelles' },
  { inseeCode: '13095', name: 'Ventabren' },
  { inseeCode: '13096', name: 'Vernègues' },
  { inseeCode: '13097', name: 'Vitrolles' },
];

export const CUSTOM_INSEE_OPTION = '__custom__';

export function isValidInseeCode(code: string): boolean {
  return /^\d{5}$/.test(code);
}

export function getCommuneLabel(inseeCode: string): string {
  const found = DEPARTMENT_COMMUNES.find((c) => c.inseeCode === inseeCode);
  return found ? `${found.name} (${inseeCode})` : inseeCode;
}
